#!/bin/sh
batteryLevel=$(cat /sys/class/power_supply/BAT0/capacity)
bstatus=$(cat /sys/class/power_supply/BAT0/status)

if [[ "$bstatus" == *Discharging* ]]
then
	statusIcon="🔋"
else
	statusIcon="🔌"
fi

echo "$statusIcon $batteryLevel%"
